server:
  port: 8080
  error:
    include-message: always

spring:
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    show-sql: true
  datasource:
    url: jdbc:postgresql://localhost:5332/pcshop
    username: stevenguyendev
    password: password
storage:
  location: /Users/stevenguyen/upload
  temp-location: /Users/stevenguyen/upload-temp
logging:
  level:
    org:
      springframework: INFO
      stevenguyendev:
        pcshopwebsite: DEBUG